specVersion: 0.2.0
name: councillor_proposals
version: 1.0.0
description: 'SubQuery: Module 3, Exercise 2'
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
      - handler: handleCouncilProposedEvent
        kind: substrate/EventHandler
        filter:
          module: council
          method: Proposed
      - handler: handleCouncilVotedEvent
        kind: substrate/EventHandler
        filter:
          module: council
          method: Voted
